use_frameworks!
platform :ios, '10.0'

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/applicaster-iap-framework'
source 'git@github.com:applicaster/applicaster-cam-framework'
source 'https://cdn.cocoapods.org/'


target 'InPlayerLoginPlugin_Example' do
  pod 'InPlayerLoginPlugin', :path => '../'

  target 'InPlayerLoginPlugin_Tests' do
    inherit! :search_paths

    
  end
end
